# Generated by Django 2.1.7 on 2019-03-25 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_remove_downloadproof_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadproof',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
